apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP #ClusterIP, NodePort ou LoadBalancer (IP Externo)
  ports:
    - name: goserver-service
      port: 80 #porta do service
      targetPort: 8000 #porta do container
      protocol: TCP
      nodePort: 30001 #30000 - 32767
